PrivacyPolicy.html
I completed the issue #1 
Kindly review and merge it. Thank you.
=> I updated sub heading in PrivacyPolicy.html

index.html
A spelling mistake got corrected.
=> typo mistake

index.html
When you say every piece of, then it means you are referring to a single noun, so you need to use singular instead of plural. Hence, 'product' instead of 'products'.
=> fix-hero-typo

css/products-responsive.css, css/products.css, css/utils.css, html/products.html, js/products.js
have a look 👇🏻  
[screen-recorder-sat-oct-01-2022-16-56-37.webm](https://user-images.githubusercontent.com/83657737/193407407-55fc79b3-ea7d-4092-b238-b7af0ec0b7cd.webm)
=> feat: product page created 

index.html
Added link to relevant section in navbar
=> Navbar buttons fix

index.html
This successfully closes #16 Feature Suggestion: Clicking on logo in footer links back to top of the page.
=> Create link to top of page from footer logo

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/doc-issue-template.md, .github/ISSUE_TEMPLATE/feature_request.md
Added issue templates for bugs, features, and documentation.
=> Update issue templates

css/style.css, index.html, js/custom.js
Loader animation is fixed and also the time of the loader is increased to 2.5 seconds
=> loader fixes

index.html
- product page linked to the index (home) page as required..
- Redirections made form (view more) button from collection section
NA
NA
=> fix:linked product.html to index.html

login.html, logincss.css
Fixes CSS Clipping on Login//Registration Container Form (See screenshot below)
Closes #56 
Touches up the CSS for the Login//Registration Container Form.
Specifically, 
N/A
Before:
After:
=> Fixes CSS Clipping

css/style.css, index.html, js/custom.js
Closes #50 
I've used the pink colour gradient for the scroll bar.
=> scroll-bar-addition 

css/style.css
This PR closes #31 issue
When we focus on any contact form field- 
**Before** - 
**After** -
=> Make `contact form` more intuitive

login.html
This PR closes #70 and #68 both
This PR solves both issues because after linking to `theme.js` file from `login page`, we are getting the correct theme behavior in the login page, which was missing before.
1. `Login` menu item will be active on the login page. 
2. Hovering on social icons is same as the home page
**Current menu in login page**
**Current footer social icons**
=> Active login menu item in login page

js/products.js
Closes #58
Changed the code for productImg in products.js
src for another active element (like buttom) was being applied to the productImg which showed a different image in the HTML
- [x ] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.
- [ x] I am a participant of Hacktoberfest 2022.
I think I can provide a solid backend using NodeJS and MongoDB to the project. So if you wanna move forward hmu.
=> Fixed Products.html bug

index.html, login.html
Added links to all the buttons now every button working properly and removed signin button from signin page 
Pr for #64
=> Now Contact button working

PrivacyPolicy.html, css/privacyPolicy.css, css/style.css
I've added a few classes to improve the basic structure of the project, and also made it responsive.
=> design structure and responsiveness is improved

index.html
In customer review section description typo was fixed.
Sania Khan's customer review has typo that I fixed.
N/A
=> Customer Review section description fixed

html/products.html
products.html file navbar have anchor link which wasn't working.
In navbar the path of the anchor tag is totally different which leads toward Can't get this page error. So I fixed that bug.
N/A
=> production.html navbar link fixed

css/style.css, index.html
Closes #74 
I added hover effects on cards (scales images and adds a background)
I inserted a call to action that leads to the product page
And I fixed the path of the images, before they were in a background in a div. Now they are in html as best practices
=> added hover effs in categories cards

css/style.css, index.html, js/index.js, logincss.css
=> Added scroll to top feature

css/style.css, login.html
* Added improved hover states on the links.
* Added scale hover effect to arrival-pictures
* Added pointer cursor to links in the site
New Card Hover state:
New hover state:
Please merge this PR if approved.
=> Added General changes proposed

css/style.css, index.html
Changed the color of the text in offer section
As previously it was hard to read the text of a section. By changing some color it is now readable
=> Changed the colour of featured section regarding issue 

index.html, js/carousal.js, js/custom.js
=> Added carousal in customer review

css/responsive.css, css/style.css, index.html
hello @KiranAminPanjwani 
i have fixed issue #120  added the reset button for the form.Please go through it and than you can accept my merge request.
=> Reset Buttton Added

index.html
I have improvised the description of the contact us section .
=> Changes Commited

css/about.css, html/about.html
I have created a counter that will take the stats from 0 to the specified number.
=> Counter Stats on About Us Page

js/custom.js
=> removed console.log

logincss.css
#162 
1)I have changed the colour of register btn's text on hovering to orange which sync with the background of the website
2)Also, I have made the colour of the forgot password text to  red so, that it is  clearly visible to user
- [x ] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.
- [x ] I am a participant of Hacktoberfest 2022.
N/A
=> Changes are made to the the colour of the btn

css/style.css, index.html, logincss.css
=> Made improvement in search bar
